apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: pdns 
  name: haproxy-pgs
  labels:
    app: haproxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: haproxy
      tier: backend
  template:
    metadata:
      labels:
        app: haproxy
        tier: backend
    spec:
      containers:
      - name: haproxy
        image: haproxy:2.8-alpine
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            memory: "128Mi"
            cpu: "50m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        ports:
            - name: http
              protocol: TCP 
              containerPort: 80
        volumeMounts:
            - mountPath: /var/log/haproxy.log
              name: harpoxy-log
            - mountPath: "/usr/local/etc/haproxy/"
              name: haproxy-cfg
              readOnly: true
        command: ["sh"]
        args: ["-c", "haproxy -f /usr/local/etc/haproxy/haproxy.cfg"]
      volumes:
          - name: harpoxy-log
            persistentVolumeClaim:
              claimName: harpoxy-log-claim
          - name: haproxy-cfg
            configMap:
              name: haproxy-config

