apiVersion: v1
kind: Service
metadata:
  namespace: pdns
  name: haproxy-pgs-service
  labels:
    app: haproxy
    tier: backend
spec:
  type: NodePort
  selector:
    app: haproxy
    tier: backend
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: 7000
    nodePort: 30001
